#!/bin/sh

# This file was generated by the Jython installer
# Created on Tue Oct 09 15:40:30 PDT 2007 by kuehnel

CLASSPATH=$(echo . ./lib/*.jar | sed 's/ /:/g')
CP="/home/kuehnel/jython/jython.jar"
if [ ! -z "$CLASSPATH" ]
then
  CP=$CP:$CLASSPATH
fi
"rm" *.class
"java" -Xmx256m -Dsun.java2d.noddraw=true -Dpython.home="/home/kuehnel/jython" -classpath "$CP" org.python.util.jython "$@"
